language: python

python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev' # 3.5 development branch

install: pip install keyrings.alt coveralls

script: travis_retry coverage run setup.py test

after_success: coveralls
